# permissions for end users to edit platforminfos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: platforminfo-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pika
    app.kubernetes.io/part-of: pika
    app.kubernetes.io/managed-by: kustomize
  name: platforminfo-editor-role
rules:
- apiGroups:
  - ngn2.nvidia.com
  resources:
  - platforminfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ngn2.nvidia.com
  resources:
  - platforminfos/status
  verbs:
  - get
